
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <vector> 
#include <list>
#include <algorithm>
#include <cstring>
#include <string>
#include <iterator>
#include <random>


using namespace std;

class User
{

private:
    string name;
    int userID; //generated by default
    string password;
    static int counterUser;
    
public:
    User();
    User(string n, string pass);
    ~User();
    void setName(string userName);
    string getName();
    void setPassword(string userPassword);
    string getPassword();
    int getUserID();
    static int getCounterUser();
    static void setCounterUser(int count);
    
};




/*
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <vector> 
#include <list>
#include <algorithm>
#include <cstring>
#include <string>
#include <iterator>



using namespace std;



public:
    static int counter;
    User() ;
    User(string username, string name, string Password) ;

    int getUserID() ;

    string getUsername() ;

    string getname() ;

    string getPassword() ;


    void createChat(User* user2);


    void sendMessage(string& chatID, string content, string senderID, bool found);





*/
   

